import type { Metadata } from 'next'
import Link from 'next/link'
import { AlertTriangle } from 'lucide-react'
import { PageHero } from '@/components/content/page-hero'
import { allSites } from '@/lib/heritage/query'

export const metadata: Metadata = { title: 'Conservation stewardship', description: 'A clearly labelled demonstration of Bharatverse conservation workflows.' }

export default function ConservationPage() {
  const sites = allSites()
  const inspections = sites.reduce((sum, site) => sum + site.conservation.inspections.length, 0)
  const indicators = sites.reduce((sum, site) => sum + site.conservation.indicators.length, 0)
  return <main className="mx-auto max-w-[110rem] px-5 pb-24 pt-28 md:px-8"><PageHero eyebrow="Stewardship mode" title="Conservation evidence without synthetic certainty." lede="This platform-level view demonstrates how institutions could review indicators, candidate findings and comparison layers while preserving human approval and data-class labels." /><div className="my-10 flex items-start gap-4 border-2 border-accent bg-accent/8 p-5"><AlertTriangle className="mt-0.5 size-6 shrink-0 text-accent" /><div><h2 className="font-sans text-sm font-medium uppercase tracking-[0.16em] text-accent">Demonstration data — not monument condition</h2><p className="mt-2 max-w-[80ch] text-sm leading-relaxed text-muted-foreground">Every health index, indicator and inspection shown below is synthetic fixture data created to exercise the workflow. It is not a measurement, site inspection or conservation finding.</p></div></div><dl className="grid gap-px border border-border/70 bg-border/70 sm:grid-cols-3">{[['Sites in demo', sites.length], ['Synthetic indicators', indicators], ['Demo inspection records', inspections]].map(([label, value]) => <div key={String(label)} className="bg-background p-6"><dt className="label-meta">{label}</dt><dd className="mt-2 font-serif text-4xl text-accent">{value}</dd></div>)}</dl><ul className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{sites.map((site) => <li key={site.id} className="border border-border/70 bg-card/20 p-6"><div className="flex items-center justify-between gap-3"><h2 className="font-serif text-2xl">{site.name}</h2><span className="border border-accent/50 px-2 py-1 text-[0.625rem] uppercase text-accent">Demo synthetic</span></div><p className="mt-2 text-xs uppercase tracking-[0.14em] text-muted-foreground">{site.city} · {site.state}</p><div className="mt-5 flex items-end gap-3"><span className="font-serif text-5xl text-primary">{site.conservation.healthIndex ?? '—'}</span><span className="pb-1 text-xs text-muted-foreground">synthetic index / 100</span></div><p className="mt-4 text-sm text-muted-foreground">{site.conservation.indicators.length} indicators · {site.conservation.inspections.length} candidate records</p><Link href={`/site/${site.slug}`} className="mt-5 inline-flex min-h-11 items-center border border-border px-3 text-xs uppercase tracking-[0.14em] text-accent">Open stewardship workspace</Link></li>)}</ul></main>
}
