import type { HeritageSite } from './types'

/**
 * Curated digital-twin dataset.
 *
 * Factual fields are drawn from institutional sources registered in
 * `lib/heritage/sources.ts` (UNESCO World Heritage Centre, Archaeological Survey
 * of India, Ministry of Culture, Ministry of Tourism). Operational fields that
 * change frequently — ticket prices, opening hours, crowd levels — are `null`
 * because they are not verifiable from a static dataset, and the UI renders them
 * as "Information not yet verified."
 *
 * Conservation inspection records are explicitly `DEMO_SYNTHETIC`. They exist to
 * exercise the review workflow and MUST NOT be read as heritage findings.
 */
export const SITES: HeritageSite[] = [
  {
    id: 'site-taj-mahal',
    slug: 'taj-mahal',
    name: 'Taj Mahal',
    localName: 'ताज महल',
    state: 'Uttar Pradesh',
    city: 'Agra',
    lat: 27.1751,
    lon: 78.0421,
    unescoRef: '252',
    inscribed: '1983',
    era: 'Mughal',
    period: '1631–1653 CE',
    tradition: 'Indo-Islamic (Mughal) funerary architecture',
    summary:
      'A white marble mausoleum built by the Mughal emperor Shah Jahan for his wife Mumtaz Mahal, set within a walled riverfront charbagh on the right bank of the Yamuna at Agra.',
    heroLine: 'A tomb built as an argument about eternity.',
    materials: ['Makrana marble', 'Red sandstone', 'Inlaid semi-precious stone (pietra dura)'],
    palette: { stone: '#e8e2d6', accent: '#c98a5c', sky: '#1b1a22' },
    facts: [
      {
        id: 'f-patron',
        label: 'Patron',
        value: 'Emperor Shah Jahan, in memory of Mumtaz Mahal',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-252', 'asi'],
      },
      {
        id: 'f-build',
        label: 'Construction',
        value: 'Mausoleum built 1631–1648; the wider complex completed around 1653',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-252'],
      },
      {
        id: 'f-architect',
        label: 'Attributed architect',
        value: 'Traditionally attributed to Ustad Ahmad Lahauri; attribution is debated in scholarship',
        evidence: 'INTERPRETATION',
        sourceIds: ['unesco-252'],
      },
      {
        id: 'f-plan',
        label: 'Plan',
        value:
          'Square mausoleum with chamfered corners on a raised plinth, four detached minarets, flanked by a mosque and a jawab, within a four-part garden',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-252', 'asi'],
      },
      {
        id: 'f-status',
        label: 'Protection',
        value: 'Centrally protected monument of national importance; UNESCO World Heritage List ref. 252',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['asi', 'unesco-252'],
      },
    ],
    twin: {
      archetype: 'TOMB_DOME',
      provenance: 'REFERENCE_RECONSTRUCTION',
      provenanceNote:
        'Massing model built from published plans and institutional descriptions. This is a reference reconstruction for orientation and storytelling — it is not a survey-grade scan and must not be measured against.',
      interiorLevel: 5,
      interiorNote:
        'No authorized interior scan is registered for this site. The chamber, paired cenotaph reference forms, jali enclosure and floral inlay panels are typological reconstructions linked to verified descriptions.',
    },
    hotspots: [
      {
        id: 'hs-dome',
        name: 'Central double dome',
        kind: 'ARCHITECTURE',
        position: [0, 26, 0],
        camera: { position: [16, 26, 34], target: [0, 20, 0] },
        summary:
          'The bulbous dome is a double shell: an outer profile shaped for the skyline and an inner dome shaped for the cenotaph chamber below, crowned by a finial.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-252'],
      },
      {
        id: 'hs-iwan',
        name: 'Great iwan portal',
        kind: 'ARCHITECTURE',
        position: [0, 11, 9],
        camera: { position: [0, 12, 30], target: [0, 10, 0] },
        summary:
          'A deep recessed arch frames the entrance on each face, bordered by calligraphic panels inlaid in black stone on white marble.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-252', 'asi'],
        spaceId: 'sp-plinth',
      },
      {
        id: 'hs-calligraphy',
        name: 'Quranic calligraphy bands',
        kind: 'INSCRIPTION',
        position: [3.4, 13.5, 9.2],
        camera: { position: [7, 14, 22], target: [3, 13, 6] },
        summary:
          'Inscriptional bands carry Quranic passages in inlaid black marble, with letter size graded upward so the text reads evenly from the ground.',
        evidence: 'INTERPRETATION',
        sourceIds: ['unesco-252'],
      },
      {
        id: 'hs-minaret',
        name: 'Detached minaret',
        kind: 'ARCHITECTURE',
        position: [12, 14, 12],
        camera: { position: [26, 16, 28], target: [12, 12, 12] },
        summary:
          'Four minarets stand clear of the mausoleum at the plinth corners, each in three stages with a crowning kiosk.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-252'],
      },
      {
        id: 'hs-pietra',
        name: 'Pietra dura inlay',
        kind: 'MATERIAL',
        position: [-5, 7, 9.2],
        camera: { position: [-9, 7.5, 20], target: [-5, 7, 6] },
        summary:
          'Floral and arabesque motifs are cut into the marble and filled with coloured stone, a technique used across dado panels and screens.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-252', 'asi'],
      },
    ],
    spaces: [
      {
        id: 'sp-gate',
        name: 'Great Gate (Darwaza-i rauza)',
        parentId: null,
        kind: 'ENTRANCE',
        plan: { x: 0.42, y: 0.82, w: 0.16, h: 0.12 },
        narrative:
          'The monumental gateway controls the first view of the mausoleum, framing it at the end of the garden axis.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-252'],
      },
      {
        id: 'sp-charbagh',
        name: 'Charbagh garden',
        parentId: 'sp-gate',
        kind: 'COURTYARD',
        plan: { x: 0.2, y: 0.46, w: 0.6, h: 0.32 },
        narrative:
          'A four-part garden divided by water channels leads from the gateway to the plinth, with a central raised tank on the axis.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-252'],
      },
      {
        id: 'sp-plinth',
        name: 'Marble plinth terrace',
        parentId: 'sp-charbagh',
        kind: 'TERRACE',
        plan: { x: 0.28, y: 0.24, w: 0.44, h: 0.18 },
        narrative:
          'The raised terrace carries the mausoleum and the four minarets, and opens to the river frontage behind.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-252'],
      },
      {
        id: 'sp-cenotaph',
        name: 'Cenotaph chamber',
        parentId: 'sp-plinth',
        kind: 'CHAMBER',
        plan: { x: 0.4, y: 0.08, w: 0.2, h: 0.14 },
        narrative:
          'An octagonal chamber holds the cenotaphs of Mumtaz Mahal and Shah Jahan behind a pierced marble screen; the actual graves lie in a lower chamber.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-252', 'asi'],
      },
      {
        id: 'sp-mosque',
        name: 'Mosque and jawab',
        parentId: 'sp-plinth',
        kind: 'HALL',
        plan: { x: 0.06, y: 0.24, w: 0.16, h: 0.18 },
        narrative:
          'Two matching red sandstone buildings flank the mausoleum — a working mosque to the west and its formal answer to the east.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-252'],
      },
    ],
    timeline: [
      {
        id: 'tl-1631',
        year: '1631',
        anchor: 1631,
        title: 'Work begins',
        detail: 'Construction of the mausoleum starts on a riverfront site at Agra after the death of Mumtaz Mahal.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-252'],
        twinState: 'FOUNDATION',
      },
      {
        id: 'tl-1648',
        year: '1648',
        anchor: 1648,
        title: 'Mausoleum completed',
        detail: 'The marble mausoleum reaches completion; work continues on the surrounding complex.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-252'],
        twinState: 'CONSTRUCTION',
      },
      {
        id: 'tl-1653',
        year: 'c. 1653',
        anchor: 1653,
        title: 'Complex finished',
        detail: 'The gateway, garden, mosque and jawab are complete, forming the walled ensemble seen today.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-252'],
        twinState: 'COMPLETE',
      },
      {
        id: 'tl-1983',
        year: '1983',
        anchor: 1983,
        title: 'World Heritage inscription',
        detail: 'Inscribed on the UNESCO World Heritage List as reference 252.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-252'],
        twinState: 'COMPLETE',
      },
    ],
    stories: [
      {
        mode: 'THIRTY_SECOND',
        label: '30 seconds',
        body:
          'Shah Jahan lost his wife Mumtaz Mahal in 1631. What he built next was not simply a grave: it was a garden, a gateway, a mosque and a marble mausoleum arranged so that the whole landscape points at one room. Every axis in the complex is an argument that memory can be built.',
        evidence: 'AI_ASSISTED_SUMMARY',
        sourceIds: ['unesco-252'],
      },
      {
        mode: 'SCHOLAR',
        label: 'Scholar',
        body:
          'The complex synthesises Timurid garden-tomb precedent with Mughal imperial idiom: a hasht-bihisht derived plan, chamfered corners, a double-shell dome, and calligraphic programme integrated with pietra dura surface work. Its riverfront terrace typology situates it within a wider Agra landscape of waterfront gardens rather than as an isolated object.',
        evidence: 'INTERPRETATION',
        sourceIds: ['unesco-252'],
      },
      {
        mode: 'CHILD',
        label: 'For children',
        body:
          'A long time ago an emperor missed someone very much. So he asked thousands of builders to make the most beautiful building they could imagine, out of white stone that changes colour with the sky. Look for the four tall towers — they lean slightly outward.',
        evidence: 'AI_ASSISTED_SUMMARY',
        sourceIds: ['unesco-252'],
      },
    ],
    conservation: {
      dataClass: 'DEMO_SYNTHETIC',
      healthIndex: 74,
      indicators: [
        { id: 'ci-surface', label: 'Surface soiling', score: 62, trend: 'DECLINING', note: 'Synthetic fixture for workflow testing.' },
        { id: 'ci-structure', label: 'Structural stability', score: 88, trend: 'STABLE', note: 'Synthetic fixture for workflow testing.' },
        { id: 'ci-water', label: 'Water ingress', score: 71, trend: 'STABLE', note: 'Synthetic fixture for workflow testing.' },
        { id: 'ci-visitor', label: 'Visitor pressure', score: 58, trend: 'DECLINING', note: 'Synthetic fixture for workflow testing.' },
      ],
      inspections: [
        {
          id: 'ir-1',
          date: '2026-05-12',
          inspector: 'Demo inspector A',
          zone: 'North dado panels',
          finding: 'Candidate discolouration band flagged by the change-detection model.',
          severity: 'MEDIUM',
          status: 'UNDER_REVIEW',
          cvConfidence: 0.71,
          reviewedBy: null,
          dataClass: 'DEMO_SYNTHETIC',
        },
        {
          id: 'ir-2',
          date: '2026-03-02',
          inspector: 'Demo inspector B',
          zone: 'Minaret 3, stage 2',
          finding: 'Hairline joint separation candidate; requires human verification.',
          severity: 'LOW',
          status: 'CANDIDATE',
          cvConfidence: 0.44,
          reviewedBy: null,
          dataClass: 'DEMO_SYNTHETIC',
        },
        {
          id: 'ir-3',
          date: '2025-11-19',
          inspector: 'Demo inspector A',
          zone: 'Plinth south edge',
          finding: 'Candidate rejected after review — shadow artefact in source imagery.',
          severity: 'LOW',
          status: 'REJECTED',
          cvConfidence: 0.36,
          reviewedBy: 'Demo reviewer',
          dataClass: 'DEMO_SYNTHETIC',
        },
      ],
      comparison: {
        label: 'Surface condition comparison',
        beforeLabel: 'Reference layer',
        afterLabel: 'Current layer',
        note: 'Synthetic layers demonstrating the comparison tool. No real inspection imagery is rehosted.',
      },
    },
    visit: {
      openingHours: null,
      ticketing: null,
      bestTime: null,
      accessibility: null,
      nearestTransit: null,
    },
    sourceIds: ['unesco-252', 'asi', 'asi-tickets', 'incredible-india'],
  },

  {
    id: 'site-hampi',
    slug: 'hampi',
    name: 'Group of Monuments at Hampi',
    localName: 'ಹಂಪೆ',
    state: 'Karnataka',
    city: 'Hampi',
    lat: 15.335,
    lon: 76.46,
    unescoRef: '241',
    inscribed: '1986',
    era: 'Vijayanagara',
    period: '14th–16th century CE',
    tradition: 'Dravidian temple architecture of the Vijayanagara empire',
    summary:
      'The austere granite landscape of the last capital of the Vijayanagara empire, holding temple complexes, colonnaded bazaars, water structures and civic buildings across the Tungabhadra valley.',
    heroLine: 'A capital city written into boulders.',
    materials: ['Granite', 'Lime plaster', 'Brick and mortar superstructure'],
    palette: { stone: '#c9b291', accent: '#d0703c', sky: '#1a1720' },
    facts: [
      {
        id: 'f-capital',
        label: 'Historical role',
        value: 'Last capital of the Vijayanagara empire, at its height in the 15th–16th centuries',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-241'],
      },
      {
        id: 'f-1565',
        label: 'Decline',
        value: 'The city was conquered and sacked in 1565 following the Battle of Talikota and was subsequently abandoned',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-241'],
      },
      {
        id: 'f-vittala',
        label: 'Signature monument',
        value: 'The Vittala temple complex, with its stone chariot shrine and colonnaded halls',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-241', 'asi'],
      },
      {
        id: 'f-water',
        label: 'Water systems',
        value: 'Aqueducts, tanks and stepped water structures distributed across the urban landscape',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-241'],
      },
    ],
    twin: {
      archetype: 'RUIN_COMPLEX',
      provenance: 'REFERENCE_RECONSTRUCTION',
      provenanceNote:
        'Stylised massing of a representative temple compound, including the stone chariot and columned halls. Individual carvings are not survey replicas.',
      interiorLevel: 5,
      interiorNote:
        'The mandapa is a typological reference reconstruction. The central Vitthala figure communicates the documented Vishnu dedication but is explicitly interpretive, not a replica of a surviving cult image.',
    },
    hotspots: [
      {
        id: 'hs-gopura',
        name: 'Temple gopura',
        kind: 'ARCHITECTURE',
        position: [0, 16, 10],
        camera: { position: [4, 16, 36], target: [0, 12, 4] },
        summary:
          'A tiered gateway tower of brick and plaster over a granite base marks the entrance to the temple enclosure.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-241'],
      },
      {
        id: 'hs-chariot',
        name: 'Stone chariot shrine',
        kind: 'SCULPTURE',
        position: [-9, 3, -2],
        camera: { position: [-16, 6, 14], target: [-9, 3, -2] },
        summary:
          'A shrine carved in the form of a processional chariot, assembled from granite blocks with wheel discs at its base.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-241', 'asi'],
      },
      {
        id: 'hs-pillars',
        name: 'Colonnaded mandapa',
        kind: 'ARCHITECTURE',
        position: [8, 4, 2],
        camera: { position: [18, 6, 16], target: [8, 3, 2] },
        summary:
          'Composite piers carry the hall roof; clustered slender shafts are cut from single granite blocks.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-241'],
      },
      {
        id: 'hs-bazaar',
        name: 'Colonnaded bazaar street',
        kind: 'CULTURAL',
        position: [0, 2, 22],
        camera: { position: [0, 8, 44], target: [0, 2, 18] },
        summary:
          'A long axial street lined with pillared shelters records the commercial life of the capital rather than only its ritual life.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-241'],
      },
    ],
    spaces: [
      {
        id: 'sp-h-gate',
        name: 'Eastern gateway',
        parentId: null,
        kind: 'ENTRANCE',
        plan: { x: 0.44, y: 0.84, w: 0.14, h: 0.1 },
        narrative: 'The gateway tower opens the enclosure onto the bazaar street.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-241'],
      },
      {
        id: 'sp-h-court',
        name: 'Temple courtyard',
        parentId: 'sp-h-gate',
        kind: 'COURTYARD',
        plan: { x: 0.16, y: 0.4, w: 0.68, h: 0.38 },
        narrative: 'An enclosed court holds the principal shrine, subsidiary shrines and the chariot.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-241'],
      },
      {
        id: 'sp-h-mandapa',
        name: 'Maha mandapa',
        parentId: 'sp-h-court',
        kind: 'HALL',
        plan: { x: 0.5, y: 0.2, w: 0.28, h: 0.16 },
        narrative: 'The great hall carries composite piers with musical and mythological registers.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-241'],
      },
      {
        id: 'sp-h-sanctum',
        name: 'Sanctum',
        parentId: 'sp-h-mandapa',
        kind: 'SANCTUM',
        plan: { x: 0.58, y: 0.06, w: 0.14, h: 0.12 },
        narrative: 'The innermost cell sits on the temple axis, deliberately dark and small.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-241'],
      },
      {
        id: 'sp-h-bazaar',
        name: 'Bazaar street',
        parentId: 'sp-h-gate',
        kind: 'GALLERY',
        plan: { x: 0.2, y: 0.9, w: 0.6, h: 0.07 },
        narrative: 'Pillared shelters line the ceremonial and commercial approach.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-241'],
      },
    ],
    timeline: [
      {
        id: 'tl-h-1336',
        year: 'c. 1336',
        anchor: 1336,
        title: 'Vijayanagara founded',
        detail: 'A new capital rises in the Tungabhadra valley, using the granite landscape as both quarry and defence.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-241'],
        twinState: 'FOUNDATION',
      },
      {
        id: 'tl-h-15c',
        year: '15th–16th c.',
        anchor: 1500,
        title: 'Imperial expansion',
        detail: 'Temple complexes, bazaars, water systems and civic architecture reach their fullest extent.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-241'],
        twinState: 'COMPLETE',
      },
      {
        id: 'tl-h-1565',
        year: '1565',
        anchor: 1565,
        title: 'Conquest and abandonment',
        detail: 'After the Battle of Talikota the city is sacked and left largely deserted.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-241'],
        twinState: 'DAMAGED',
      },
      {
        id: 'tl-h-1986',
        year: '1986',
        anchor: 1986,
        title: 'World Heritage inscription',
        detail: 'Inscribed on the UNESCO World Heritage List as reference 241.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-241'],
        twinState: 'DAMAGED',
      },
    ],
    stories: [
      {
        mode: 'THIRTY_SECOND',
        label: '30 seconds',
        body:
          'Hampi is not a monument. It is a city that stopped. Granite boulders were carved into gateways, streets, temples and water tanks — and then, after 1565, left alone. Walking it is closer to reading an interrupted sentence than visiting a ruin.',
        evidence: 'AI_ASSISTED_SUMMARY',
        sourceIds: ['unesco-241'],
      },
      {
        mode: 'SCHOLAR',
        label: 'Scholar',
        body:
          'The site is best read as an urban landscape: sacred centre, royal centre, and the hydraulic infrastructure that made both viable. Vijayanagara architectural idiom combines granite structural work with brick-and-plaster superstructures, and its pier types are a chronological marker across the empire.',
        evidence: 'INTERPRETATION',
        sourceIds: ['unesco-241'],
      },
      {
        mode: 'FOLKLORE',
        label: 'Folklore',
        body:
          'Local tradition connects the surrounding hills with episodes of the Ramayana, and the region is popularly identified with Kishkindha. This is recorded as living tradition, not as archaeological finding.',
        evidence: 'ORAL_TRADITION',
        sourceIds: ['unesco-241'],
      },
    ],
    conservation: {
      dataClass: 'DEMO_SYNTHETIC',
      healthIndex: 66,
      indicators: [
        { id: 'ci-h-1', label: 'Masonry displacement', score: 61, trend: 'STABLE', note: 'Synthetic fixture.' },
        { id: 'ci-h-2', label: 'Vegetation intrusion', score: 54, trend: 'DECLINING', note: 'Synthetic fixture.' },
        { id: 'ci-h-3', label: 'Plaster loss', score: 49, trend: 'DECLINING', note: 'Synthetic fixture.' },
        { id: 'ci-h-4', label: 'Site drainage', score: 78, trend: 'IMPROVING', note: 'Synthetic fixture.' },
      ],
      inspections: [
        {
          id: 'ir-h-1',
          date: '2026-06-04',
          inspector: 'Demo inspector C',
          zone: 'Mandapa pier row 4',
          finding: 'Candidate spalling flagged on two piers.',
          severity: 'MEDIUM',
          status: 'CANDIDATE',
          cvConfidence: 0.63,
          reviewedBy: null,
          dataClass: 'DEMO_SYNTHETIC',
        },
        {
          id: 'ir-h-2',
          date: '2026-01-22',
          inspector: 'Demo inspector C',
          zone: 'Bazaar street north',
          finding: 'Root intrusion candidate confirmed by reviewer in demo workflow.',
          severity: 'HIGH',
          status: 'CONFIRMED',
          cvConfidence: 0.82,
          reviewedBy: 'Demo reviewer',
          dataClass: 'DEMO_SYNTHETIC',
        },
      ],
      comparison: {
        label: 'Vegetation growth comparison',
        beforeLabel: 'Reference layer',
        afterLabel: 'Current layer',
        note: 'Synthetic layers demonstrating the comparison tool.',
      },
    },
    visit: {
      openingHours: null,
      ticketing: null,
      bestTime: null,
      accessibility: null,
      nearestTransit: null,
    },
    sourceIds: ['unesco-241', 'asi', 'incredible-india'],
  },

  {
    id: 'site-konark',
    slug: 'konark-sun-temple',
    name: 'Sun Temple, Konark',
    localName: 'କୋଣାର୍କ ସୂର୍ଯ୍ୟ ମନ୍ଦିର',
    state: 'Odisha',
    city: 'Konark',
    lat: 19.8876,
    lon: 86.0945,
    unescoRef: '246',
    inscribed: '1984',
    era: 'Eastern Ganga',
    period: '13th century CE',
    tradition: 'Kalinga temple architecture',
    summary:
      'A 13th-century temple to the sun god Surya, conceived as a colossal chariot with carved wheels and drawn by horses, on the Odisha coast.',
    heroLine: 'A temple built as a chariot for the sun.',
    materials: ['Khondalite', 'Chlorite', 'Laterite'],
    palette: { stone: '#a98a6b', accent: '#c2622f', sky: '#171a24' },
    facts: [
      {
        id: 'f-k-patron',
        label: 'Patron',
        value: 'Attributed to King Narasimhadeva I of the Eastern Ganga dynasty, 13th century',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-246', 'asi'],
      },
      {
        id: 'f-k-form',
        label: 'Conception',
        value: 'The temple is designed as the chariot of Surya, with carved wheels along the plinth and horses at the approach',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-246'],
      },
      {
        id: 'f-k-deul',
        label: 'Condition',
        value: 'The principal tower (deul) has collapsed; the assembly hall (jagamohana) survives as the dominant standing structure',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-246', 'asi'],
      },
      {
        id: 'f-k-navigation',
        label: 'Maritime association',
        value: 'The temple was historically noted by mariners on the Odisha coast',
        evidence: 'INTERPRETATION',
        sourceIds: ['unesco-246'],
      },
    ],
    twin: {
      archetype: 'CHARIOT',
      provenance: 'REFERENCE_RECONSTRUCTION',
      provenanceNote:
        'Massing reconstruction of the surviving jagamohana and plinth wheels from published documentation. The collapsed deul is shown only in the timeline reconstruction state and is labelled as such.',
      interiorLevel: 4,
      interiorNote:
        'The surviving hall, Surya reference image, sculptural registers and collapsed deul footprint are schematic rather than a scan. The inaccessible inner volume is not presented as an exact visitor record.',
    },
    hotspots: [
      {
        id: 'hs-k-wheel',
        name: 'Chariot wheel',
        kind: 'SCULPTURE',
        position: [10, 3, 8],
        camera: { position: [20, 5, 20], target: [10, 3, 8] },
        summary:
          'Carved wheels are set along the plinth, each with spokes, hub and decorated rim; they are among the most recognised elements of Kalinga sculpture.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-246'],
      },
      {
        id: 'hs-k-jagamohana',
        name: 'Jagamohana roof',
        kind: 'ARCHITECTURE',
        position: [0, 20, 0],
        camera: { position: [14, 22, 34], target: [0, 16, 0] },
        summary:
          'The pyramidal roof rises in receding tiers with recessed courses, a signature of the Kalinga pidha form.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-246'],
      },
      {
        id: 'hs-k-horse',
        name: 'Horse sculpture',
        kind: 'SCULPTURE',
        position: [0, 3, 20],
        camera: { position: [8, 6, 34], target: [0, 3, 20] },
        summary: 'Monumental horses are placed at the approach, completing the chariot metaphor.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-246', 'asi'],
      },
      {
        id: 'hs-k-collapse',
        name: 'Site of the collapsed deul',
        kind: 'CONSERVATION',
        position: [-14, 6, 0],
        camera: { position: [-26, 12, 18], target: [-14, 4, 0] },
        summary:
          'The principal tower no longer stands. Its former footprint is a conservation and interpretation subject, not a reconstruction claim.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-246', 'asi'],
      },
    ],
    spaces: [
      {
        id: 'sp-k-approach',
        name: 'Eastern approach',
        parentId: null,
        kind: 'ENTRANCE',
        plan: { x: 0.42, y: 0.86, w: 0.16, h: 0.1 },
        narrative: 'The approach aligns the temple with the sunrise over the coast.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-246'],
      },
      {
        id: 'sp-k-natmandir',
        name: 'Dance hall platform',
        parentId: 'sp-k-approach',
        kind: 'HALL',
        plan: { x: 0.36, y: 0.62, w: 0.28, h: 0.18 },
        narrative: 'A detached platform on the axis carries relief registers of musicians and dancers.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-246'],
      },
      {
        id: 'sp-k-jagamohana',
        name: 'Jagamohana (assembly hall)',
        parentId: 'sp-k-natmandir',
        kind: 'HALL',
        plan: { x: 0.34, y: 0.32, w: 0.32, h: 0.24 },
        narrative:
          'The surviving hall was filled in during later consolidation work to prevent collapse, so its interior is not open.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Interior not publicly accessible.',
        sourceIds: ['unesco-246', 'asi'],
      },
      {
        id: 'sp-k-deul',
        name: 'Deul footprint',
        parentId: 'sp-k-jagamohana',
        kind: 'SANCTUM',
        plan: { x: 0.38, y: 0.1, w: 0.24, h: 0.18 },
        narrative: 'The sanctuary tower is lost; only its lower structure and footprint remain.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-246'],
      },
    ],
    timeline: [
      {
        id: 'tl-k-13c',
        year: '13th c.',
        anchor: 1250,
        title: 'Temple constructed',
        detail: 'The chariot temple is built on the Odisha coast under Eastern Ganga patronage.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-246'],
        twinState: 'COMPLETE',
      },
      {
        id: 'tl-k-loss',
        year: 'Later centuries',
        anchor: 1700,
        title: 'Loss of the principal tower',
        detail:
          'The deul collapses. The precise cause and date are debated in scholarship and are not asserted here as fact.',
        evidence: 'INTERPRETATION',
        sourceIds: ['unesco-246'],
        twinState: 'DAMAGED',
      },
      {
        id: 'tl-k-consolidation',
        year: 'Early 20th c.',
        anchor: 1910,
        title: 'Consolidation works',
        detail: 'Conservation interventions stabilise the surviving hall.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['asi'],
        twinState: 'RESTORED',
      },
      {
        id: 'tl-k-1984',
        year: '1984',
        anchor: 1984,
        title: 'World Heritage inscription',
        detail: 'Inscribed on the UNESCO World Heritage List as reference 246.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-246'],
        twinState: 'RESTORED',
      },
    ],
    stories: [
      {
        mode: 'THIRTY_SECOND',
        label: '30 seconds',
        body:
          'Konark is a building that pretends to be a vehicle. Wheels along its base, horses at its front, and an axis pointed at the rising sun. The tallest part of it fell centuries ago — what remains is still enormous.',
        evidence: 'AI_ASSISTED_SUMMARY',
        sourceIds: ['unesco-246'],
      },
      {
        mode: 'SCHOLAR',
        label: 'Scholar',
        body:
          'The temple represents a late and ambitious phase of Kalinga architecture, where iconographic programme and structural form converge: the rekha deul and pidha jagamohana are integrated with a chariot conceit executed at architectural scale.',
        evidence: 'INTERPRETATION',
        sourceIds: ['unesco-246'],
      },
    ],
    conservation: {
      dataClass: 'DEMO_SYNTHETIC',
      healthIndex: 59,
      indicators: [
        { id: 'ci-k-1', label: 'Salt weathering', score: 44, trend: 'DECLINING', note: 'Synthetic fixture.' },
        { id: 'ci-k-2', label: 'Stone erosion', score: 51, trend: 'DECLINING', note: 'Synthetic fixture.' },
        { id: 'ci-k-3', label: 'Structural stability', score: 72, trend: 'STABLE', note: 'Synthetic fixture.' },
        { id: 'ci-k-4', label: 'Sculptural detail loss', score: 47, trend: 'DECLINING', note: 'Synthetic fixture.' },
      ],
      inspections: [
        {
          id: 'ir-k-1',
          date: '2026-07-08',
          inspector: 'Demo inspector D',
          zone: 'South wheel 3',
          finding: 'Candidate surface loss on rim carving.',
          severity: 'HIGH',
          status: 'UNDER_REVIEW',
          cvConfidence: 0.77,
          reviewedBy: null,
          dataClass: 'DEMO_SYNTHETIC',
        },
      ],
      comparison: {
        label: 'Coastal weathering comparison',
        beforeLabel: 'Reference layer',
        afterLabel: 'Current layer',
        note: 'Synthetic layers demonstrating the comparison tool.',
      },
    },
    visit: {
      openingHours: null,
      ticketing: null,
      bestTime: null,
      accessibility: null,
      nearestTransit: null,
    },
    sourceIds: ['unesco-246', 'asi', 'incredible-india'],
  },

  {
    id: 'site-ajanta',
    slug: 'ajanta-caves',
    name: 'Ajanta Caves',
    localName: 'अजिंठा लेणी',
    state: 'Maharashtra',
    city: 'Aurangabad district',
    lat: 20.5519,
    lon: 75.7033,
    unescoRef: '242',
    inscribed: '1983',
    era: 'Satavahana and Vakataka',
    period: '2nd century BCE – 6th century CE',
    tradition: 'Buddhist rock-cut architecture and painting',
    summary:
      'A horseshoe scarp above the Waghora river cut with Buddhist prayer halls and monasteries, carrying some of the most important surviving Indian mural painting.',
    heroLine: 'Architecture made by removing stone, not stacking it.',
    materials: ['Basalt (excavated)', 'Lime plaster ground', 'Mineral pigments'],
    palette: { stone: '#8f7f6a', accent: '#b4562f', sky: '#14161d' },
    facts: [
      {
        id: 'f-a-phases',
        label: 'Phases',
        value: 'Excavated in two broad phases, from around the 2nd century BCE and again from about the 5th century CE',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-242'],
      },
      {
        id: 'f-a-types',
        label: 'Cave types',
        value: 'Chaitya prayer halls with stupas, and vihara monastic halls with surrounding cells',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-242', 'asi'],
      },
      {
        id: 'f-a-paintings',
        label: 'Paintings',
        value: 'Wall and ceiling paintings depicting Jataka narratives and Buddhist iconography survive in several caves',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-242'],
      },
      {
        id: 'f-a-rediscovery',
        label: 'Modern rediscovery',
        value: 'Brought to wider modern attention in 1819 after being encountered by a British hunting party',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['asi', 'unesco-242'],
      },
    ],
    twin: {
      archetype: 'ROCK_CUT',
      provenance: 'REFERENCE_RECONSTRUCTION',
      provenanceNote:
        'Sectional representation of a chaitya hall type derived from published architectural documentation. Paintings are not reproduced; they are referenced through institutional sources.',
      interiorLevel: 4,
      interiorNote:
        'Interior is represented as a documented hall-type reconstruction with a stupa, a representative Buddha-image gallery and offering vessels, clearly separated from any claim of one exact cave.',
    },
    hotspots: [
      {
        id: 'hs-a-facade',
        name: 'Chaitya window facade',
        kind: 'ARCHITECTURE',
        position: [0, 12, 12],
        camera: { position: [0, 12, 40], target: [0, 10, 4] },
        summary:
          'A horseshoe-arched window above the entrance admits light along the hall axis toward the stupa.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-242'],
      },
      {
        id: 'hs-a-stupa',
        name: 'Rock-cut stupa',
        kind: 'ARTEFACT',
        position: [0, 5, -16],
        camera: { position: [0, 7, 4], target: [0, 5, -16] },
        summary:
          'The stupa stands at the apse end, carved from the living rock rather than assembled.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-242', 'asi'],
      },
      {
        id: 'hs-a-colonnade',
        name: 'Aisle colonnade',
        kind: 'ARCHITECTURE',
        position: [7, 5, -4],
        camera: { position: [16, 6, 8], target: [6, 4, -4] },
        summary:
          'Two rows of pillars separate the nave from ambulatory aisles, allowing circumambulation of the stupa.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-242'],
      },
      {
        id: 'hs-a-painting',
        name: 'Painted surface',
        kind: 'MATERIAL',
        position: [-7, 7, -6],
        camera: { position: [-14, 7, 6], target: [-7, 6, -6] },
        summary:
          'Paint was applied on a prepared plaster ground over rough-cut basalt. Painted surfaces are extremely fragile and light-sensitive.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-242', 'asi'],
      },
    ],
    spaces: [
      {
        id: 'sp-a-approach',
        name: 'Scarp walkway',
        parentId: null,
        kind: 'ENTRANCE',
        plan: { x: 0.08, y: 0.88, w: 0.84, h: 0.07 },
        narrative: 'A path along the ravine links the caves in sequence above the river bend.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-242'],
      },
      {
        id: 'sp-a-veranda',
        name: 'Veranda',
        parentId: 'sp-a-approach',
        kind: 'ENTRANCE',
        plan: { x: 0.34, y: 0.7, w: 0.32, h: 0.1 },
        narrative: 'A pillared porch mediates between the ravine light and the dark interior.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-242'],
      },
      {
        id: 'sp-a-nave',
        name: 'Chaitya nave',
        parentId: 'sp-a-veranda',
        kind: 'HALL',
        plan: { x: 0.38, y: 0.26, w: 0.24, h: 0.4 },
        narrative: 'The barrel-vaulted nave draws the eye down the axis toward the stupa.',
        evidence: 'RECONSTRUCTION',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-242'],
      },
      {
        id: 'sp-a-aisle',
        name: 'Ambulatory aisles',
        parentId: 'sp-a-nave',
        kind: 'GALLERY',
        plan: { x: 0.28, y: 0.26, w: 0.08, h: 0.4 },
        narrative: 'Narrow aisles behind the colonnade allow ritual circumambulation.',
        evidence: 'RECONSTRUCTION',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-242'],
      },
      {
        id: 'sp-a-apse',
        name: 'Apse with stupa',
        parentId: 'sp-a-nave',
        kind: 'SANCTUM',
        plan: { x: 0.4, y: 0.1, w: 0.2, h: 0.14 },
        narrative: 'The semicircular apse holds the monolithic stupa.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-242'],
      },
    ],
    timeline: [
      {
        id: 'tl-a-1',
        year: 'c. 2nd c. BCE',
        anchor: -150,
        title: 'First phase of excavation',
        detail: 'Early caves are cut into the scarp, establishing the chaitya and vihara types.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-242'],
        twinState: 'FOUNDATION',
      },
      {
        id: 'tl-a-2',
        year: 'c. 5th c. CE',
        anchor: 450,
        title: 'Second phase',
        detail: 'A major later phase produces the most elaborate halls and the best-preserved paintings.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-242'],
        twinState: 'COMPLETE',
      },
      {
        id: 'tl-a-3',
        year: '1819',
        anchor: 1819,
        title: 'Modern rediscovery',
        detail: 'The caves re-enter wider modern record after centuries of relative obscurity.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['asi'],
        twinState: 'DAMAGED',
      },
      {
        id: 'tl-a-4',
        year: '1983',
        anchor: 1983,
        title: 'World Heritage inscription',
        detail: 'Inscribed on the UNESCO World Heritage List as reference 242.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-242'],
        twinState: 'RESTORED',
      },
    ],
    stories: [
      {
        mode: 'THIRTY_SECOND',
        label: '30 seconds',
        body:
          'At Ajanta, builders worked backwards. Instead of raising walls, they removed a hillside — cutting halls, pillars and a stupa from solid basalt, then painting the walls. The result is a building that was never assembled.',
        evidence: 'AI_ASSISTED_SUMMARY',
        sourceIds: ['unesco-242'],
      },
      {
        mode: 'SCHOLAR',
        label: 'Scholar',
        body:
          'Ajanta is central to the study of Indian painting because it preserves a sequence rather than a single moment, allowing comparative analysis of pigment, ground preparation, narrative composition and iconographic development across phases.',
        evidence: 'INTERPRETATION',
        sourceIds: ['unesco-242'],
      },
    ],
    conservation: {
      dataClass: 'DEMO_SYNTHETIC',
      healthIndex: 63,
      indicators: [
        { id: 'ci-a-1', label: 'Paint layer stability', score: 42, trend: 'DECLINING', note: 'Synthetic fixture.' },
        { id: 'ci-a-2', label: 'Humidity control', score: 57, trend: 'STABLE', note: 'Synthetic fixture.' },
        { id: 'ci-a-3', label: 'Rock mass stability', score: 81, trend: 'STABLE', note: 'Synthetic fixture.' },
        { id: 'ci-a-4', label: 'Visitor load', score: 60, trend: 'STABLE', note: 'Synthetic fixture.' },
      ],
      inspections: [
        {
          id: 'ir-a-1',
          date: '2026-04-30',
          inspector: 'Demo inspector E',
          zone: 'Nave ceiling, bay 2',
          finding: 'Candidate plaster detachment area flagged for specialist review.',
          severity: 'HIGH',
          status: 'UNDER_REVIEW',
          cvConfidence: 0.68,
          reviewedBy: null,
          dataClass: 'DEMO_SYNTHETIC',
        },
      ],
      comparison: {
        label: 'Painted surface comparison',
        beforeLabel: 'Reference layer',
        afterLabel: 'Current layer',
        note: 'Synthetic layers demonstrating the comparison tool.',
      },
    },
    visit: {
      openingHours: null,
      ticketing: null,
      bestTime: null,
      accessibility: null,
      nearestTransit: null,
    },
    sourceIds: ['unesco-242', 'asi', 'incredible-india'],
  },

  {
    id: 'site-khajuraho',
    slug: 'khajuraho',
    name: 'Khajuraho Group of Monuments',
    localName: 'खजुराहो',
    state: 'Madhya Pradesh',
    city: 'Khajuraho',
    lat: 24.8318,
    lon: 79.9199,
    unescoRef: '240',
    inscribed: '1986',
    era: 'Chandela',
    period: 'c. 950–1050 CE',
    tradition: 'Nagara temple architecture',
    summary:
      'A group of Hindu and Jain temples built under the Chandela dynasty, known for integrated sculptural programmes and clearly articulated Nagara plans and towers.',
    heroLine: 'Sculpture and structure designed as one system.',
    materials: ['Sandstone', 'Granite (early foundations)'],
    palette: { stone: '#c8a882', accent: '#c06a3a', sky: '#191722' },
    facts: [
      {
        id: 'f-kh-dynasty',
        label: 'Patronage',
        value: 'Built under the Chandela dynasty, largely between about 950 and 1050 CE',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-240'],
      },
      {
        id: 'f-kh-count',
        label: 'Surviving temples',
        value: 'About twenty temples survive from a considerably larger original group',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-240', 'asi'],
      },
      {
        id: 'f-kh-plan',
        label: 'Architectural type',
        value: 'Nagara temples on raised platforms with entrance porch, hall, vestibule and sanctum under a shikhara',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-240'],
      },
      {
        id: 'f-kh-religions',
        label: 'Religious affiliation',
        value: 'The group includes both Hindu and Jain temples',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-240'],
      },
    ],
    twin: {
      archetype: 'SHIKHARA',
      provenance: 'REFERENCE_RECONSTRUCTION',
      provenanceNote:
        'Massing reconstruction of a representative Nagara temple with clustered shikhara. Sculptural registers are indicated abstractly and are not documentation of specific carvings.',
      interiorLevel: 5,
      interiorNote:
        'The hall sequence, lotus ceiling, sculptural register and Shiva-linga reference form are a Kandariya-inspired typological reading; they do not claim to reproduce every Hindu and Jain temple in the group.',
    },
    hotspots: [
      {
        id: 'hs-kh-shikhara',
        name: 'Clustered shikhara',
        kind: 'ARCHITECTURE',
        position: [0, 24, -4],
        camera: { position: [14, 24, 30], target: [0, 18, -4] },
        summary:
          'The tower is built up from many smaller replicated turrets, producing a mountain-like silhouette over the sanctum.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-240'],
      },
      {
        id: 'hs-kh-platform',
        name: 'Raised platform (jagati)',
        kind: 'ARCHITECTURE',
        position: [0, 2, 14],
        camera: { position: [0, 8, 38], target: [0, 2, 10] },
        summary:
          'Each temple stands on a high platform without a surrounding enclosure wall, so the whole elevation stays visible.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-240'],
      },
      {
        id: 'hs-kh-registers',
        name: 'Sculptural registers',
        kind: 'SCULPTURE',
        position: [8, 9, 6],
        camera: { position: [18, 10, 20], target: [8, 8, 6] },
        summary:
          'Horizontal bands of figural sculpture wrap the walls, integrated with the mouldings rather than applied to them.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-240', 'asi'],
      },
      {
        id: 'hs-kh-sanctum',
        name: 'Sanctum doorway',
        kind: 'ARCHITECTURE',
        position: [0, 6, 2],
        camera: { position: [0, 7, 20], target: [0, 6, -2] },
        summary:
          'The axial sequence from porch to sanctum compresses progressively, ending in a small dark cell.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-240'],
      },
    ],
    spaces: [
      {
        id: 'sp-kh-porch',
        name: 'Ardhamandapa (porch)',
        parentId: null,
        kind: 'ENTRANCE',
        plan: { x: 0.42, y: 0.82, w: 0.16, h: 0.1 },
        narrative: 'The entrance porch begins the axial sequence.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-240'],
      },
      {
        id: 'sp-kh-mandapa',
        name: 'Mandapa',
        parentId: 'sp-kh-porch',
        kind: 'HALL',
        plan: { x: 0.34, y: 0.56, w: 0.32, h: 0.22 },
        narrative: 'The pillared hall carries a decorated ceiling and lateral balconies.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-240'],
      },
      {
        id: 'sp-kh-maha',
        name: 'Mahamandapa',
        parentId: 'sp-kh-mandapa',
        kind: 'HALL',
        plan: { x: 0.32, y: 0.34, w: 0.36, h: 0.2 },
        narrative: 'A larger hall with transepts widens the plan before the sanctum.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-240'],
      },
      {
        id: 'sp-kh-garbha',
        name: 'Garbhagriha (sanctum)',
        parentId: 'sp-kh-maha',
        kind: 'SANCTUM',
        plan: { x: 0.42, y: 0.14, w: 0.16, h: 0.16 },
        narrative: 'The sanctum sits beneath the shikhara, with an ambulatory in the larger temples.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-240'],
      },
    ],
    timeline: [
      {
        id: 'tl-kh-1',
        year: 'c. 950',
        anchor: 950,
        title: 'Chandela building programme begins',
        detail: 'Temple construction begins at the Chandela centre.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-240'],
        twinState: 'FOUNDATION',
      },
      {
        id: 'tl-kh-2',
        year: 'c. 1050',
        anchor: 1050,
        title: 'Mature phase',
        detail: 'The largest temples, including the principal Shaiva temple, are completed.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-240'],
        twinState: 'COMPLETE',
      },
      {
        id: 'tl-kh-3',
        year: '1986',
        anchor: 1986,
        title: 'World Heritage inscription',
        detail: 'Inscribed on the UNESCO World Heritage List as reference 240.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-240'],
        twinState: 'COMPLETE',
      },
    ],
    stories: [
      {
        mode: 'THIRTY_SECOND',
        label: '30 seconds',
        body:
          'Khajuraho is often reduced to a single subject. Architecturally it is something more precise: a place where plan, elevation, tower and sculpture were designed as one continuous system, so that the building reads as a modelled mass rather than decorated walls.',
        evidence: 'AI_ASSISTED_SUMMARY',
        sourceIds: ['unesco-240'],
      },
      {
        mode: 'SCHOLAR',
        label: 'Scholar',
        body:
          'The temples exemplify a mature Central Indian Nagara idiom: pancharatha and saptaratha wall articulation, latina-derived shikhara built up from urahshringas, and an axial sequence coordinated with sculptural registers.',
        evidence: 'INTERPRETATION',
        sourceIds: ['unesco-240'],
      },
    ],
    conservation: {
      dataClass: 'DEMO_SYNTHETIC',
      healthIndex: 71,
      indicators: [
        { id: 'ci-kh-1', label: 'Sandstone erosion', score: 58, trend: 'DECLINING', note: 'Synthetic fixture.' },
        { id: 'ci-kh-2', label: 'Biological growth', score: 66, trend: 'STABLE', note: 'Synthetic fixture.' },
        { id: 'ci-kh-3', label: 'Structural stability', score: 84, trend: 'STABLE', note: 'Synthetic fixture.' },
        { id: 'ci-kh-4', label: 'Platform drainage', score: 74, trend: 'IMPROVING', note: 'Synthetic fixture.' },
      ],
      inspections: [
        {
          id: 'ir-kh-1',
          date: '2026-02-14',
          inspector: 'Demo inspector F',
          zone: 'North wall register 2',
          finding: 'Candidate erosion band flagged; awaiting review.',
          severity: 'MEDIUM',
          status: 'CANDIDATE',
          cvConfidence: 0.55,
          reviewedBy: null,
          dataClass: 'DEMO_SYNTHETIC',
        },
      ],
      comparison: {
        label: 'Surface erosion comparison',
        beforeLabel: 'Reference layer',
        afterLabel: 'Current layer',
        note: 'Synthetic layers demonstrating the comparison tool.',
      },
    },
    visit: {
      openingHours: null,
      ticketing: null,
      bestTime: null,
      accessibility: null,
      nearestTransit: null,
    },
    sourceIds: ['unesco-240', 'asi', 'incredible-india'],
  },

  {
    id: 'site-qutb',
    slug: 'qutb-minar',
    name: 'Qutb Minar and its Monuments',
    localName: 'क़ुतुब मीनार',
    state: 'Delhi',
    city: 'Delhi',
    lat: 28.5245,
    lon: 77.1855,
    unescoRef: '233',
    inscribed: '1993',
    era: 'Delhi Sultanate',
    period: 'Begun 1199 CE, with later additions',
    tradition: 'Early Indo-Islamic architecture',
    summary:
      'A tapering fluted minaret of red sandstone and marble, standing within a complex that includes an early congregational mosque, tombs, gateways and an earlier iron pillar.',
    heroLine: 'The tallest sentence in early Indo-Islamic architecture.',
    materials: ['Red sandstone', 'Marble', 'Reused earlier masonry'],
    palette: { stone: '#b8734a', accent: '#e0b46a', sky: '#181620' },
    facts: [
      {
        id: 'f-q-height',
        label: 'Height',
        value: 'The minaret rises to about 72.5 metres in five tapering storeys',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-233', 'asi'],
      },
      {
        id: 'f-q-start',
        label: 'Construction',
        value: 'Begun in 1199 under Qutb-ud-din Aibak and continued by Iltutmish, with later repairs and additions',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-233'],
      },
      {
        id: 'f-q-mosque',
        label: 'Associated mosque',
        value: 'The adjacent Quwwat-ul-Islam mosque incorporates columns and material reused from earlier structures',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-233', 'asi'],
      },
      {
        id: 'f-q-iron',
        label: 'Iron Pillar',
        value: 'An earlier iron pillar with a Sanskrit inscription stands in the mosque courtyard',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-233', 'asi'],
      },
    ],
    twin: {
      archetype: 'MINARET',
      provenance: 'REFERENCE_RECONSTRUCTION',
      provenanceNote:
        'Massing reconstruction of the minaret and adjoining courtyard from published descriptions and dimensions. The Iron Pillar, fluting and inscription bands are reference forms, not survey data.',
      interiorLevel: 4,
      interiorNote:
        'The minaret remains closed to visitors. Its compact base chamber and spiral stair are a schematic spatial interpretation, clearly separated from any claim of an authorized capture.',
    },
    hotspots: [
      {
        id: 'hs-q-storeys',
        name: 'Five tapering storeys',
        kind: 'ARCHITECTURE',
        position: [0, 36, 3],
        camera: { position: [22, 38, 40], target: [0, 30, 0] },
        summary:
          'Each storey is separated by a projecting balcony on carved corbels, and the shaft narrows as it rises.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-233'],
      },
      {
        id: 'hs-q-inscription',
        name: 'Inscription bands',
        kind: 'INSCRIPTION',
        position: [2.6, 14, 2.6],
        camera: { position: [10, 15, 16], target: [2, 14, 2] },
        summary:
          'Bands of carved inscription wrap the shaft, recording construction and later repair campaigns.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-233', 'asi'],
      },
      {
        id: 'hs-q-mosque',
        name: 'Mosque courtyard colonnade',
        kind: 'ARCHITECTURE',
        position: [-16, 4, 8],
        camera: { position: [-28, 9, 26], target: [-16, 3, 8] },
        summary:
          'Reused columns of earlier temples carry the courtyard colonnade, making the mosque a document of its own construction history.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-233'],
      },
      {
        id: 'hs-q-iron',
        name: 'Iron Pillar',
        kind: 'ARTEFACT',
        position: [-14, 4, -4],
        camera: { position: [-22, 6, 8], target: [-14, 4, -4] },
        summary:
          'A corrosion-resistant iron pillar predating the complex stands in the courtyard, carrying a Sanskrit inscription.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-233', 'asi'],
      },
    ],
    spaces: [
      {
        id: 'sp-q-entry',
        name: 'Complex entrance',
        parentId: null,
        kind: 'ENTRANCE',
        plan: { x: 0.44, y: 0.86, w: 0.14, h: 0.1 },
        narrative: 'The visitor route enters the archaeological complex from the east.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-233'],
      },
      {
        id: 'sp-q-courtyard',
        name: 'Mosque courtyard',
        parentId: 'sp-q-entry',
        kind: 'COURTYARD',
        plan: { x: 0.1, y: 0.4, w: 0.46, h: 0.4 },
        narrative: 'The congregational courtyard holds the Iron Pillar and is framed by reused colonnades.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-233'],
      },
      {
        id: 'sp-q-screen',
        name: 'Arched screen',
        parentId: 'sp-q-courtyard',
        kind: 'GALLERY',
        plan: { x: 0.1, y: 0.3, w: 0.46, h: 0.08 },
        narrative: 'A monumental arched screen faces the courtyard on the qibla side.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-233'],
      },
      {
        id: 'sp-q-minar',
        name: 'Minaret base',
        parentId: 'sp-q-entry',
        kind: 'CHAMBER',
        plan: { x: 0.66, y: 0.5, w: 0.18, h: 0.18 },
        narrative: 'The minaret base carries the entrance to a spiral stair, now closed to visitors.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Interior stair closed to visitors.',
        sourceIds: ['unesco-233', 'asi'],
      },
    ],
    timeline: [
      {
        id: 'tl-q-1',
        year: '1199',
        anchor: 1199,
        title: 'Minaret begun',
        detail: 'Construction starts under Qutb-ud-din Aibak.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-233'],
        twinState: 'FOUNDATION',
      },
      {
        id: 'tl-q-2',
        year: '13th c.',
        anchor: 1230,
        title: 'Completion by Iltutmish',
        detail: 'The upper storeys are added, and the mosque complex is extended.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-233'],
        twinState: 'CONSTRUCTION',
      },
      {
        id: 'tl-q-3',
        year: '14th c. onward',
        anchor: 1370,
        title: 'Repairs and additions',
        detail: 'Later sultans undertake repairs, recorded in inscriptions on the shaft.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-233', 'asi'],
        twinState: 'RESTORED',
      },
      {
        id: 'tl-q-4',
        year: '1993',
        anchor: 1993,
        title: 'World Heritage inscription',
        detail: 'Inscribed on the UNESCO World Heritage List as reference 233.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-233'],
        twinState: 'RESTORED',
      },
    ],
    stories: [
      {
        mode: 'THIRTY_SECOND',
        label: '30 seconds',
        body:
          'The Qutb complex is a building site that never fully closed. A minaret begun in 1199, a mosque assembled partly from older columns, an iron pillar older than both, and centuries of repair inscriptions climbing the shaft.',
        evidence: 'AI_ASSISTED_SUMMARY',
        sourceIds: ['unesco-233'],
      },
      {
        mode: 'SCHOLAR',
        label: 'Scholar',
        body:
          'The complex is a primary document for the formation of Indo-Islamic architecture in northern India: spolia use, corbelled arcuation preceding true arch construction, and epigraphy functioning as both ornament and administrative record.',
        evidence: 'INTERPRETATION',
        sourceIds: ['unesco-233'],
      },
    ],
    conservation: {
      dataClass: 'DEMO_SYNTHETIC',
      healthIndex: 77,
      indicators: [
        { id: 'ci-q-1', label: 'Shaft masonry', score: 80, trend: 'STABLE', note: 'Synthetic fixture.' },
        { id: 'ci-q-2', label: 'Balcony corbels', score: 68, trend: 'STABLE', note: 'Synthetic fixture.' },
        { id: 'ci-q-3', label: 'Air quality exposure', score: 55, trend: 'DECLINING', note: 'Synthetic fixture.' },
        { id: 'ci-q-4', label: 'Courtyard colonnade', score: 72, trend: 'STABLE', note: 'Synthetic fixture.' },
      ],
      inspections: [
        {
          id: 'ir-q-1',
          date: '2026-06-27',
          inspector: 'Demo inspector G',
          zone: 'Storey 2 balcony',
          finding: 'Candidate soiling accumulation flagged on corbel underside.',
          severity: 'LOW',
          status: 'UNDER_REVIEW',
          cvConfidence: 0.49,
          reviewedBy: null,
          dataClass: 'DEMO_SYNTHETIC',
        },
      ],
      comparison: {
        label: 'Soiling comparison',
        beforeLabel: 'Reference layer',
        afterLabel: 'Current layer',
        note: 'Synthetic layers demonstrating the comparison tool.',
      },
    },
    visit: {
      openingHours: null,
      ticketing: null,
      bestTime: null,
      accessibility: null,
      nearestTransit: null,
    },
    sourceIds: ['unesco-233', 'asi', 'asi-tickets'],
  },

  {
    id: 'site-thanjavur',
    slug: 'brihadisvara-thanjavur',
    name: 'Brihadisvara Temple, Thanjavur',
    localName: 'பெருவுடையார் கோவில்',
    state: 'Tamil Nadu',
    city: 'Thanjavur',
    lat: 10.7828,
    lon: 79.1318,
    unescoRef: '250',
    inscribed: '1987',
    era: 'Chola',
    period: 'Completed c. 1010 CE',
    tradition: 'Dravidian temple architecture of the Chola empire',
    summary:
      'The great Chola temple built under Rajaraja I, part of the Great Living Chola Temples, with a tall pyramidal vimana over the sanctum and extensive inscriptions recording temple administration.',
    heroLine: 'An empire that wrote its accounts on its walls.',
    materials: ['Granite', 'Brick and mortar (upper elements)'],
    palette: { stone: '#bfa585', accent: '#cf7b3a', sky: '#161821' },
    facts: [
      {
        id: 'f-t-patron',
        label: 'Patron',
        value: 'Built under the Chola emperor Rajaraja I and completed around 1010 CE',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-250', 'asi'],
      },
      {
        id: 'f-t-vimana',
        label: 'Vimana',
        value: 'A tall pyramidal tower rises over the sanctum, among the tallest of its period in southern India',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-250'],
      },
      {
        id: 'f-t-inscriptions',
        label: 'Inscriptions',
        value: 'Extensive inscriptions record endowments, personnel and administration of the temple',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-250', 'asi'],
      },
      {
        id: 'f-t-living',
        label: 'Status',
        value: 'Part of the Great Living Chola Temples, a serial World Heritage property still in ritual use',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-250'],
      },
    ],
    twin: {
      archetype: 'GOPURAM',
      provenance: 'REFERENCE_RECONSTRUCTION',
      provenanceNote:
        'Massing reconstruction of the vimana, mandapa and enclosure from published documentation. Selected documented focal objects — the Nandi and great linga — are reference forms; carved surfaces are not survey replicas.',
      interiorLevel: 5,
      interiorNote:
        'Active place of worship. The linga, guardian pair, carved register and ritual furnishings are reference forms within the documented plan graph, with access notes kept visible.',
    },
    hotspots: [
      {
        id: 'hs-t-vimana',
        name: 'Vimana',
        kind: 'ARCHITECTURE',
        position: [0, 30, -2],
        camera: { position: [18, 30, 36], target: [0, 22, -2] },
        summary:
          'The tower rises in receding storeys to a monolithic capping element, expressing the sanctum below at civic scale.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-250'],
      },
      {
        id: 'hs-t-nandi',
        name: 'Nandi pavilion',
        kind: 'SCULPTURE',
        position: [0, 4, 22],
        camera: { position: [10, 7, 40], target: [0, 4, 22] },
        summary: 'A large seated Nandi faces the sanctum along the temple axis.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-250', 'asi'],
      },
      {
        id: 'hs-t-linga',
        name: 'Colossal Shiva linga',
        kind: 'ARTEFACT',
        spaceId: 'sp-t-sanctum',
        position: [0, 4, -4],
        camera: { position: [0, 5, 8], target: [0, 3, -4] },
        summary:
          'A massive linga occupies the centre of the sanctum, encircled by a dark circumambulatory passage inside the vimana.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-250'],
      },
      {
        id: 'hs-t-inscription',
        name: 'Inscription wall',
        kind: 'INSCRIPTION',
        position: [-10, 4, 6],
        camera: { position: [-20, 6, 20], target: [-10, 4, 6] },
        summary:
          'Long inscriptional registers turn the temple into an administrative archive as much as a religious building.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-250', 'asi'],
      },
      {
        id: 'hs-t-gopura',
        name: 'Entrance gopura',
        kind: 'ARCHITECTURE',
        position: [0, 14, 34],
        camera: { position: [0, 16, 58], target: [0, 12, 32] },
        summary: 'Gateway towers on the enclosure mark the transition into the temple precinct.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-250'],
      },
    ],
    spaces: [
      {
        id: 'sp-t-gopura',
        name: 'Gopura gateway',
        parentId: null,
        kind: 'ENTRANCE',
        plan: { x: 0.42, y: 0.88, w: 0.16, h: 0.08 },
        narrative: 'The gateway sequence controls entry into the enclosure.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-250'],
      },
      {
        id: 'sp-t-prakara',
        name: 'Prakara courtyard',
        parentId: 'sp-t-gopura',
        kind: 'COURTYARD',
        plan: { x: 0.14, y: 0.34, w: 0.72, h: 0.48 },
        narrative: 'A colonnaded enclosure surrounds the main temple with subsidiary shrines.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-250'],
      },
      {
        id: 'sp-t-mandapa',
        name: 'Mahamandapa',
        parentId: 'sp-t-prakara',
        kind: 'HALL',
        plan: { x: 0.38, y: 0.44, w: 0.24, h: 0.18 },
        narrative: 'The pillared hall precedes the sanctum on the main axis.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-250'],
      },
      {
        id: 'sp-t-sanctum',
        name: 'Garbhagriha',
        parentId: 'sp-t-mandapa',
        kind: 'SANCTUM',
        plan: { x: 0.4, y: 0.2, w: 0.2, h: 0.2 },
        narrative:
          'The sanctum is in active worship; access is governed by temple practice rather than by heritage ticketing.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Access governed by temple practice.',
        sourceIds: ['unesco-250'],
      },
    ],
    timeline: [
      {
        id: 'tl-t-1',
        year: 'c. 1003',
        anchor: 1003,
        title: 'Construction begins',
        detail: 'Work starts on the imperial Chola temple at Thanjavur.',
        evidence: 'INTERPRETATION',
        sourceIds: ['unesco-250'],
        twinState: 'FOUNDATION',
      },
      {
        id: 'tl-t-2',
        year: 'c. 1010',
        anchor: 1010,
        title: 'Temple completed',
        detail: 'The temple is completed under Rajaraja I.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-250'],
        twinState: 'COMPLETE',
      },
      {
        id: 'tl-t-3',
        year: '1987',
        anchor: 1987,
        title: 'World Heritage inscription',
        detail: 'Inscribed as part of the Great Living Chola Temples, reference 250.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-250'],
        twinState: 'COMPLETE',
      },
    ],
    stories: [
      {
        mode: 'THIRTY_SECOND',
        label: '30 seconds',
        body:
          'Thanjavur is a temple that keeps records. Its walls carry inscriptions listing land grants, staff and endowments — so the building is simultaneously a monument, an archive, and a working place of worship a thousand years later.',
        evidence: 'AI_ASSISTED_SUMMARY',
        sourceIds: ['unesco-250'],
      },
      {
        mode: 'SCHOLAR',
        label: 'Scholar',
        body:
          'The temple is central to Chola studies: its epigraphic corpus documents temple economy and administrative structure, while its vimana demonstrates the structural ambition of early eleventh-century Dravidian practice.',
        evidence: 'INTERPRETATION',
        sourceIds: ['unesco-250'],
      },
    ],
    conservation: {
      dataClass: 'DEMO_SYNTHETIC',
      healthIndex: 80,
      indicators: [
        { id: 'ci-t-1', label: 'Granite condition', score: 86, trend: 'STABLE', note: 'Synthetic fixture.' },
        { id: 'ci-t-2', label: 'Inscription legibility', score: 64, trend: 'DECLINING', note: 'Synthetic fixture.' },
        { id: 'ci-t-3', label: 'Ritual-use wear', score: 70, trend: 'STABLE', note: 'Synthetic fixture.' },
        { id: 'ci-t-4', label: 'Enclosure drainage', score: 82, trend: 'IMPROVING', note: 'Synthetic fixture.' },
      ],
      inspections: [
        {
          id: 'ir-t-1',
          date: '2026-05-05',
          inspector: 'Demo inspector H',
          zone: 'South inscription register',
          finding: 'Candidate legibility loss flagged for epigraphic review.',
          severity: 'MEDIUM',
          status: 'CANDIDATE',
          cvConfidence: 0.58,
          reviewedBy: null,
          dataClass: 'DEMO_SYNTHETIC',
        },
      ],
      comparison: {
        label: 'Inscription legibility comparison',
        beforeLabel: 'Reference layer',
        afterLabel: 'Current layer',
        note: 'Synthetic layers demonstrating the comparison tool.',
      },
    },
    visit: {
      openingHours: null,
      ticketing: null,
      bestTime: null,
      accessibility: null,
      nearestTransit: null,
    },
    sourceIds: ['unesco-250', 'asi', 'incredible-india'],
  },

  {
    id: 'site-mahabalipuram',
    slug: 'mahabalipuram',
    name: 'Group of Monuments at Mahabalipuram',
    localName: 'மாமல்லபுரம்',
    state: 'Tamil Nadu',
    city: 'Mamallapuram',
    lat: 12.6208,
    lon: 80.1945,
    unescoRef: '249',
    inscribed: '1984',
    era: 'Pallava',
    period: '7th–8th century CE',
    tradition: 'Pallava rock-cut and structural temple architecture',
    summary:
      'A coastal group of Pallava monuments including rock-cut cave temples, monolithic rathas, large open-air reliefs and the structural Shore Temple.',
    heroLine: 'A workshop where Indian temple form was prototyped.',
    materials: ['Granite (monolithic and structural)'],
    palette: { stone: '#c0a184', accent: '#c9803f', sky: '#151a22' },
    facts: [
      {
        id: 'f-m-dynasty',
        label: 'Patronage',
        value: 'Created under the Pallava dynasty in the 7th and 8th centuries CE',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-249'],
      },
      {
        id: 'f-m-rathas',
        label: 'Monolithic rathas',
        value: 'A group of temples carved from single granite outcrops, each exploring a different roof and plan type',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-249', 'asi'],
      },
      {
        id: 'f-m-relief',
        label: 'Open-air relief',
        value: 'A very large open-air rock relief, commonly known as the Descent of the Ganges or Arjuna\u2019s Penance',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-249'],
      },
      {
        id: 'f-m-shore',
        label: 'Shore Temple',
        value: 'A structural stone temple on the shoreline, distinct from the site\u2019s rock-cut monuments',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-249', 'asi'],
      },
    ],
    twin: {
      archetype: 'RUIN_COMPLEX',
      provenance: 'REFERENCE_RECONSTRUCTION',
      provenanceNote:
        'Stylised massing of the shoreline temple group and adjacent monoliths from published documentation. The monolithic ratha and shrine focal object are reference forms; relief carving is not a survey replica.',
      interiorLevel: 5,
      interiorNote:
        'The shallow cave hall, principal shrine, Nandi frieze, guardian pair and ritual furnishings are typological reference forms represented through the documented plan sequence.',
    },
    hotspots: [
      {
        id: 'hs-m-shore',
        name: 'Shore Temple',
        kind: 'ARCHITECTURE',
        position: [0, 14, 0],
        camera: { position: [16, 15, 32], target: [0, 10, 0] },
        summary:
          'A structural temple with stepped tower, built rather than carved, exposed to salt-laden coastal wind.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-249'],
      },
      {
        id: 'hs-m-ratha',
        name: 'Monolithic ratha',
        kind: 'ARCHITECTURE',
        position: [-14, 4, 10],
        camera: { position: [-24, 7, 26], target: [-14, 4, 10] },
        summary:
          'Each ratha tests a different temple type in a single block of stone, functioning almost as built research.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-249', 'asi'],
      },
      {
        id: 'hs-m-relief',
        name: 'Open-air relief panel',
        kind: 'SCULPTURE',
        position: [14, 6, 8],
        camera: { position: [26, 8, 24], target: [14, 5, 8] },
        summary:
          'A vast narrative relief is cut directly into a natural rock face, integrating a natural cleft into the composition.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-249'],
      },
      {
        id: 'hs-m-cave',
        name: 'Rock-cut mandapa',
        kind: 'ARCHITECTURE',
        position: [-6, 4, -12],
        camera: { position: [-14, 6, 4], target: [-6, 4, -12] },
        summary:
          'Pillared cave halls with lion-based columns show the transition from excavated to structural building.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-249'],
      },
    ],
    spaces: [
      {
        id: 'sp-m-shorefront',
        name: 'Shorefront platform',
        parentId: null,
        kind: 'ENTRANCE',
        plan: { x: 0.3, y: 0.86, w: 0.4, h: 0.1 },
        narrative: 'The temple platform meets the beach directly, shaping its conservation problem.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-249'],
      },
      {
        id: 'sp-m-court',
        name: 'Temple enclosure',
        parentId: 'sp-m-shorefront',
        kind: 'COURTYARD',
        plan: { x: 0.26, y: 0.44, w: 0.48, h: 0.36 },
        narrative: 'A low enclosure surrounds the shore temple shrines.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-249'],
      },
      {
        id: 'sp-m-shrine',
        name: 'Principal shrine',
        parentId: 'sp-m-court',
        kind: 'SANCTUM',
        plan: { x: 0.42, y: 0.22, w: 0.18, h: 0.16 },
        narrative: 'The main cell sits beneath the stepped tower.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-249'],
      },
      {
        id: 'sp-m-mandapa',
        name: 'Rock-cut mandapa',
        parentId: 'sp-m-shorefront',
        kind: 'HALL',
        plan: { x: 0.06, y: 0.5, w: 0.16, h: 0.2 },
        narrative: 'A shallow excavated hall with sculpted panels on its side walls.',
        evidence: 'VERIFIED_FACT',
        accessibility: 'Information not yet verified.',
        sourceIds: ['unesco-249'],
      },
    ],
    timeline: [
      {
        id: 'tl-m-1',
        year: '7th c.',
        anchor: 650,
        title: 'Rock-cut phase',
        detail: 'Cave temples, rathas and reliefs are cut into the granite landscape.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-249'],
        twinState: 'CONSTRUCTION',
      },
      {
        id: 'tl-m-2',
        year: '8th c.',
        anchor: 725,
        title: 'Structural phase',
        detail: 'The Shore Temple is built as a structural stone temple.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-249'],
        twinState: 'COMPLETE',
      },
      {
        id: 'tl-m-3',
        year: '1984',
        anchor: 1984,
        title: 'World Heritage inscription',
        detail: 'Inscribed on the UNESCO World Heritage List as reference 249.',
        evidence: 'VERIFIED_FACT',
        sourceIds: ['unesco-249'],
        twinState: 'COMPLETE',
      },
    ],
    stories: [
      {
        mode: 'THIRTY_SECOND',
        label: '30 seconds',
        body:
          'Mahabalipuram feels less like a finished site and more like a design studio. Different temple forms were carved from single rocks, side by side, as if the builders were testing ideas that would later be built at full scale elsewhere.',
        evidence: 'AI_ASSISTED_SUMMARY',
        sourceIds: ['unesco-249'],
      },
      {
        mode: 'SCHOLAR',
        label: 'Scholar',
        body:
          'The site documents the Pallava transition from excavated mandapas and monolithic vimana types to structural masonry construction, making it a key comparative sequence for South Indian temple typology.',
        evidence: 'INTERPRETATION',
        sourceIds: ['unesco-249'],
      },
    ],
    conservation: {
      dataClass: 'DEMO_SYNTHETIC',
      healthIndex: 61,
      indicators: [
        { id: 'ci-m-1', label: 'Salt spray exposure', score: 41, trend: 'DECLINING', note: 'Synthetic fixture.' },
        { id: 'ci-m-2', label: 'Surface pitting', score: 52, trend: 'DECLINING', note: 'Synthetic fixture.' },
        { id: 'ci-m-3', label: 'Structural stability', score: 79, trend: 'STABLE', note: 'Synthetic fixture.' },
        { id: 'ci-m-4', label: 'Shoreline protection', score: 68, trend: 'IMPROVING', note: 'Synthetic fixture.' },
      ],
      inspections: [
        {
          id: 'ir-m-1',
          date: '2026-07-19',
          inspector: 'Demo inspector I',
          zone: 'Shore Temple east face',
          finding: 'Candidate salt crystallisation flagged along lower courses.',
          severity: 'HIGH',
          status: 'CANDIDATE',
          cvConfidence: 0.74,
          reviewedBy: null,
          dataClass: 'DEMO_SYNTHETIC',
        },
      ],
      comparison: {
        label: 'Salt weathering comparison',
        beforeLabel: 'Reference layer',
        afterLabel: 'Current layer',
        note: 'Synthetic layers demonstrating the comparison tool.',
      },
    },
    visit: {
      openingHours: null,
      ticketing: null,
      bestTime: null,
      accessibility: null,
      nearestTransit: null,
    },
    sourceIds: ['unesco-249', 'asi', 'incredible-india'],
  },
]
