import type { SourceRef } from './types'

/**
 * APPROVED SOURCE REGISTRY (§14).
 *
 * Sources are registered with an explicit reuse posture. The platform links to
 * institutional sources and does not rehost their media. `LINK_ONLY` sources may
 * be cited and deep-linked but never ingested as media.
 */
export const SOURCES: SourceRef[] = [
  {
    id: 'unesco-whc',
    title: 'UNESCO World Heritage List — India',
    publisher: 'UNESCO World Heritage Centre',
    url: 'https://whc.unesco.org/en/statesparties/in',
    license: 'UNESCO terms of use',
    reuse: 'LINK_ONLY',
    lastChecked: '2026-08-18',
    scope: 'NATIONAL',
  },
  {
    id: 'unesco-252',
    title: 'Taj Mahal — World Heritage List ref. 252',
    publisher: 'UNESCO World Heritage Centre',
    url: 'https://whc.unesco.org/en/list/252/',
    license: 'UNESCO terms of use',
    reuse: 'LINK_ONLY',
    lastChecked: '2026-08-18',
    scope: 'SITE',
  },
  {
    id: 'unesco-241',
    title: 'Group of Monuments at Hampi — ref. 241',
    publisher: 'UNESCO World Heritage Centre',
    url: 'https://whc.unesco.org/en/list/241/',
    license: 'UNESCO terms of use',
    reuse: 'LINK_ONLY',
    lastChecked: '2026-08-18',
    scope: 'SITE',
  },
  {
    id: 'unesco-246',
    title: 'Sun Temple, Konârak — ref. 246',
    publisher: 'UNESCO World Heritage Centre',
    url: 'https://whc.unesco.org/en/list/246/',
    license: 'UNESCO terms of use',
    reuse: 'LINK_ONLY',
    lastChecked: '2026-08-18',
    scope: 'SITE',
  },
  {
    id: 'unesco-242',
    title: 'Ajanta Caves — ref. 242',
    publisher: 'UNESCO World Heritage Centre',
    url: 'https://whc.unesco.org/en/list/242/',
    license: 'UNESCO terms of use',
    reuse: 'LINK_ONLY',
    lastChecked: '2026-08-18',
    scope: 'SITE',
  },
  {
    id: 'unesco-240',
    title: 'Khajuraho Group of Monuments — ref. 240',
    publisher: 'UNESCO World Heritage Centre',
    url: 'https://whc.unesco.org/en/list/240/',
    license: 'UNESCO terms of use',
    reuse: 'LINK_ONLY',
    lastChecked: '2026-08-18',
    scope: 'SITE',
  },
  {
    id: 'unesco-233',
    title: 'Qutb Minar and its Monuments, Delhi — ref. 233',
    publisher: 'UNESCO World Heritage Centre',
    url: 'https://whc.unesco.org/en/list/233/',
    license: 'UNESCO terms of use',
    reuse: 'LINK_ONLY',
    lastChecked: '2026-08-18',
    scope: 'SITE',
  },
  {
    id: 'unesco-250',
    title: 'Great Living Chola Temples — ref. 250',
    publisher: 'UNESCO World Heritage Centre',
    url: 'https://whc.unesco.org/en/list/250/',
    license: 'UNESCO terms of use',
    reuse: 'LINK_ONLY',
    lastChecked: '2026-08-18',
    scope: 'SITE',
  },
  {
    id: 'unesco-249',
    title: 'Group of Monuments at Mahabalipuram — ref. 249',
    publisher: 'UNESCO World Heritage Centre',
    url: 'https://whc.unesco.org/en/list/249/',
    license: 'UNESCO terms of use',
    reuse: 'LINK_ONLY',
    lastChecked: '2026-08-18',
    scope: 'SITE',
  },
  {
    id: 'asi',
    title: 'Archaeological Survey of India — Monuments',
    publisher: 'Archaeological Survey of India, Ministry of Culture',
    url: 'https://asi.nic.in/',
    license: 'Government of India website policy',
    reuse: 'LINK_ONLY',
    lastChecked: '2026-08-18',
    scope: 'NATIONAL',
  },
  {
    id: 'asi-tickets',
    title: 'ASI Online Ticketing — monument entry information',
    publisher: 'Archaeological Survey of India',
    url: 'https://asi.payumoney.com/',
    license: 'Government of India website policy',
    reuse: 'LINK_ONLY',
    lastChecked: '2026-08-18',
    scope: 'NATIONAL',
  },
  {
    id: 'moc',
    title: 'Ministry of Culture, Government of India',
    publisher: 'Ministry of Culture',
    url: 'https://www.indiaculture.gov.in/',
    license: 'Government of India website policy',
    reuse: 'LINK_ONLY',
    lastChecked: '2026-08-18',
    scope: 'NATIONAL',
  },
  {
    id: 'incredible-india',
    title: 'Incredible India — official tourism portal',
    publisher: 'Ministry of Tourism, Government of India',
    url: 'https://www.incredibleindia.gov.in/',
    license: 'Government of India website policy',
    reuse: 'LINK_ONLY',
    lastChecked: '2026-08-18',
    scope: 'NATIONAL',
  },
  {
    id: 'nmma',
    title: 'National Mission on Monuments and Antiquities',
    publisher: 'Ministry of Culture',
    url: 'https://asi.nic.in/national-mission-on-monuments-and-antiquities/',
    license: 'Government of India website policy',
    reuse: 'LINK_ONLY',
    lastChecked: '2026-08-18',
    scope: 'NATIONAL',
  },
  {
    id: 'osm',
    title: 'OpenStreetMap — geographic base data',
    publisher: 'OpenStreetMap contributors',
    url: 'https://www.openstreetmap.org/copyright',
    license: 'Open Database License (ODbL)',
    reuse: 'ATTRIBUTION_REQUIRED',
    lastChecked: '2026-08-18',
    scope: 'GLOBAL',
  },
  {
    id: 'google-places',
    title: 'Google Places API — live business details, ratings and reviews',
    publisher: 'Google Maps Platform',
    url: 'https://developers.google.com/maps/documentation/places/web-service/overview',
    license: 'Google Maps Platform terms',
    reuse: 'ATTRIBUTION_REQUIRED',
    lastChecked: '2026-08-23',
    scope: 'GLOBAL',
  },
  {
    id: 'google-routes',
    title: 'Google Routes API — driving distance and duration',
    publisher: 'Google Maps Platform',
    url: 'https://developers.google.com/maps/documentation/routes/compute_route_matrix',
    license: 'Google Maps Platform terms',
    reuse: 'ATTRIBUTION_REQUIRED',
    lastChecked: '2026-08-23',
    scope: 'GLOBAL',
  },
  {
    id: 'groq',
    title: 'GroqCloud — grounded language-model inference',
    publisher: 'Groq, Inc.',
    url: 'https://console.groq.com/docs/models',
    license: 'GroqCloud terms',
    reuse: 'LINK_ONLY',
    lastChecked: '2026-08-23',
    scope: 'GLOBAL',
  },
  {
    id: 'bharatverse-demo',
    title: 'BHARATVERSE synthetic inspection fixture set',
    publisher: 'BHARATVERSE AI (internal, non-production)',
    url: '/about/data-policy',
    license: 'Internal demo fixture — not a heritage finding',
    reuse: 'RESTRICTED',
    lastChecked: '2026-08-18',
    scope: 'SITE',
  },
]

const INDEX = new Map(SOURCES.map((s) => [s.id, s]))

export function getSource(id: string): SourceRef | undefined {
  return INDEX.get(id)
}

export function getSources(ids: string[]): SourceRef[] {
  return ids.map((id) => INDEX.get(id)).filter((s): s is SourceRef => Boolean(s))
}
